# Generated by Django 4.1.5 on 2023-02-20 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('sub_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StravaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_strava_verified', models.BooleanField(default=False)),
                ('downloading', models.BooleanField(default=False)),
                ('has_completed_initial_download', models.BooleanField(default=False)),
                ('preferred_units', models.CharField(default='imperial', max_length=10)),
                ('pie_color_palette', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StravaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('distance_meters', models.FloatField()),
                ('moving_time_sec', models.PositiveIntegerField()),
                ('elapsed_time_sec', models.PositiveIntegerField()),
                ('total_elevation_gain_m', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('sport_type', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('timezone', models.CharField(max_length=100)),
                ('utc_offset', models.IntegerField()),
                ('location_country', models.CharField(max_length=100)),
                ('achievement_count', models.IntegerField()),
                ('kudos_count', models.IntegerField()),
                ('average_speed_mps', models.FloatField()),
                ('max_speed_mps', models.FloatField()),
                ('has_heartrate', models.BooleanField(default=False)),
                ('elev_high_m', models.FloatField()),
                ('elev_low_m', models.FloatField()),
                ('pr_count', models.IntegerField()),
                ('average_cadence', models.FloatField()),
                ('average_watts', models.FloatField()),
                ('max_watts', models.FloatField()),
                ('weighted_average_watts', models.FloatField()),
                ('kilojoules', models.FloatField()),
                ('average_heartrate', models.FloatField()),
                ('max_heartrate', models.FloatField()),
                ('suffer_score', models.FloatField()),
                ('elapsed_time_min', models.FloatField()),
                ('moving_time_min', models.FloatField(default=0.0)),
                ('elev_high_ft', models.FloatField()),
                ('elev_low_ft', models.FloatField()),
                ('elev_gain_ft', models.FloatField()),
                ('distance_miles', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('feet_per_mile', models.FloatField()),
                ('meters_per_km', models.FloatField()),
                ('average_speed_mph', models.FloatField()),
                ('average_speed_kph', models.FloatField()),
                ('max_speed_mph', models.FloatField()),
                ('max_speed_kph', models.FloatField()),
                ('average_temp', models.FloatField()),
                ('site_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
