# Generated by Django 4.1.5 on 2023-01-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
