# Generated by Django 4.1.5 on 2023-01-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_info', '0002_alter_stravaactivity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravauser',
            name='pie_color_palette',
            field=models.JSONField(default='{}'),
        ),
    ]
