# Generated by Django 4.1.5 on 2023-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_info', '0003_stravauser_pie_color_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravauser',
            name='pie_color_palette',
            field=models.JSONField(default=dict),
        ),
    ]
